const httpConfig = () => ({
  // SUCCESS RESPONSES
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  // CLIENT ERROR RESPONSES
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  MOTHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSIBLE_ENTITY: 422,
  TOO_MANY_REQUEST: 429,

  // SERVER ERROR RESPONSES
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504

})

export const HTTPSTATUS = httpConfig();

export type HttpStatusCodeType = (typeof HTTPSTATUS)[keyof typeof HTTPSTATUS]
