export const ErrorCodeEnum = {
  AUTH_EMAIL_ALREADY_EXIST: "AUTH_EMAIL_ALREADY_EXIST",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",

  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_ANAUTHORIZED_ACCESS: "AUTH_ANAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",

  // ACCESS CONTROL ERRORS
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",

  // VALIDATION AND RESOURCE ERRORS
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // SYSTEM ERROR
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

export type ErrorCodeEnumType = keyof typeof ErrorCodeEnum
